settings = {
	'root-dir' : '/Users/jah5/Documents/Fall2014_Gaspar/data',
	'comment-file-dir' : './comments',
	'mag-type' : 'TF',
	'aperture' : '1',
	'time-type' : 'BJD',
	'logfile' : 'hatvislog.dat',
	'na-str' : '---',
	'nbins' : 300,
	'dphase' : 0.05,
	'peaks-dn' : 5,
	'label-font' : ( "Helvetica", 14, "bold" ),
	'label-bg' : 'sky blue',
	'value-font' : ( "Helvetica", 14 ),
	'file-list-font' : ("monospace", 10),
	'dperiod' : 0.01,
	'entry-width' : 6,
	'nfrqs' : 1000,
	'n-peaks' : 5,
	'alpha' : 0.3,
	'bin-phase' : False,
	'remove-outliers' : True,
	'outlier-sigma' : 3.0

}
